### ISSUE TITLE
Documentation: meta pySDK operations

### ISSUE THREAD

**Issue by jagaither** [tapis-project/documentation#16]
Currently Missing meta pySDK operations in readthedocs for:

- [x]  List Indexes
- [x] Create Index
- [x] Delete Index
- [x] Create an Aggregation
- [x] Execute an Aggregation
- [x] Delete an Aggregation
