### ISSUE TITLE
Documentation: meta CURL responses

### ISSUE THREAD

**Issue by jagaither** [tapis-project/documentation#17]
The following operations have missing responses:

- [x] Create DB
- [x] Delete DB
- [x] Get Collection Size
- [x] Replace Document
- [x] Modify Document
- [x] Delete Document
- [x] List Index
- [x] Create Index
- [x] Delete Index
- [x] Create an Aggregation
- [x] Execute an Aggregation
- [x] Delete an Aggregation
